services:

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/radarr:/config
      - ./data:/data
    # ports:
    #   - 7878:7878
    networks:
      - nginx

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/sonarr:/config
      - ./data:/data
    # ports:
    #   - 8989:8989
    networks:
      - nginx

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/prowlarr:/config
    # ports:
    #   - 9696:9696
    networks:
      - nginx

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/bazarr:/config
      - ./data/tvshows:/data/tvshows
      - ./data/movies:/data/movies
    # ports:
    #   - 6767:6767
    networks:
      - nginx

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
      - PEERPORT=${TRANSMISSION_PEERPORT}
      - TZ=${TZ}
    volumes:
      - ./config/transmission:/config
      - ./data/downloads:/downloads
    ports:
      - ${TRANSMISSION_PEERPORT}:${TRANSMISSION_PEERPORT}
      - ${TRANSMISSION_PEERPORT}:${TRANSMISSION_PEERPORT}/udp
      # - 9091:9091
    networks:
      - nginx

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL} # optional
      - TZ=${TZ}
    volumes:
      - ./config/jellyfin:/config
      - ./data/tvshows:/data/tvshows
      - ./data/movies:/data/movies
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /dev/video13:/dev/video13
      - /dev/video14:/dev/video14
      - /dev/video15:/dev/video15
      - /dev/video16:/dev/video16
      - /dev/video18:/dev/video18
      - /dev/video19:/dev/video19
    ports:
      - 8096:8096
      # - 8920:8920     # optional https
      # - 7359:7359/udp # optional local discovery
      # - 1900:1900/udp # optional dnla
    networks:
      - nginx

networks:
    nginx:
      external: true
